### ISSUE TITLE
Empty spaces surrounding the images on the exported scene

### ISSUE THREAD

**Issue by senntore** [rbreu/beeref#83]
**Describe the bug**
There are lots of empty space surrounding the images on the exported scene if we move the images around or make them smaller.

**To Reproduce**
1. Import some images
2. Export without making any changes. See how there is not much empty spaces on the border.
3. Now back in the scene, move the images around or make them big & then small.
4. Export the changed scene. Notice how there are lots of empty spaces surrounding the images.

**Expected behavior**
I'm expecting the exported scene to have only the minimum margin like the first screenshot.

I believe this issue is happening because the width & height of the exported scene is considered at the maximum width & height of the scene/canvas through out it's history rather than the current farthest extent of images (or text).  

The default margin is good, so please keep it when fixing this issue.

**Screenshots**
Scene export result right after importing the images:
![example](https://github.com/rbreu/beeref/assets/58325574/9f092876-f254-451a-a571-e1e4a3f4233c)

Scene export result after making some changes & moving images around the canvas.
![example 2](https://github.com/rbreu/beeref/assets/58325574/7d7150dd-edaf-435c-b5c0-9d1e8e520973)

BeeRef version 0.3.1
Pop OS 22.04

I've been waiting for the last update & I really like this feature, so I hope it can be polished a little more.

**Comment by rbreu** [comment]
This is now fixed in the main branch and will go out with the next release.

**Comment by senntore** [comment]
@rbreu I tried testing the development version by building the project but I'm still having this issue.

I did not notice it earlier but this issue does not happen(even in 0.3.1) when I try to load a saved scene & then try to export it without making any changes.
When I do make some changes like moving the images around or resizing them, exporting the scene give me this issue during that session.

The only difference I found between the exported scene is that in version 0.3.1 the exported scene has a bigger file size & the images are of higher & original resolution and in version 0.3.2dev the exported scene is of much smaller file size & the images are of lower resolution.
Both of them have the empty spaces surrounding the images.  

There might've been some issue in building the project on my end which could be the reason I'm seeing this issue even after it's supposed to be fixed, so it would be great if you can test it once more.

**Comment by rbreu** [comment]
You are right, there were more issues than the one I fixed. I hope commit 310ca14 fixes this for good. Also, there was an issue with setup.py not grabbing all the subdirectories, that should now be fixed as well.
